# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 240)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 0, 401, 281))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_ipv6 = QtWidgets.QLabel(self.centralwidget)
        self.label_ipv6.setGeometry(QtCore.QRect(120, 20, 231, 21))
        self.label_ipv6.setObjectName("label_ipv6")
        self.label_last_update = QtWidgets.QLabel(self.centralwidget)
        self.label_last_update.setGeometry(QtCore.QRect(120, 60, 221, 21))
        self.label_last_update.setObjectName("label_last_update")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_last_check = QtWidgets.QLabel(self.centralwidget)
        self.label_last_check.setGeometry(QtCore.QRect(120, 150, 181, 21))
        self.label_last_check.setObjectName("label_last_check")
        self.textEdit_period = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_period.setGeometry(QtCore.QRect(120, 100, 113, 20))
        self.textEdit_period.setObjectName("textEdit_period")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "My IPV6:"))
        self.label_2.setText(_translate("MainWindow", "Last upload:"))
        self.label_3.setText(_translate("MainWindow", "Check Period:"))
        self.label_ipv6.setText(_translate("MainWindow", "2001:da8:201d:1101:9382:454f:3e18:d131"))
        self.label_last_update.setText(_translate("MainWindow", "2020"))
        self.label_4.setText(_translate("MainWindow", "last check:"))
        self.label_last_check.setText(_translate("MainWindow", "2020"))
        self.textEdit_period.setText(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
